# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-13 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('otp', models.CharField(max_length=200)),
                ('timestamp', models.CharField(max_length=200)),
                ('project_id', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Registration')),
            ],
        ),
    ]
