# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-13 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='employee_id',
            field=models.CharField(max_length=200),
        ),
    ]
