# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-23 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191013_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(max_length=200)),
                ('shop_longitude', models.CharField(max_length=200)),
                ('shop_lattitude', models.CharField(max_length=200)),
            ],
        ),
    ]
