# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-25 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191120_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='shop_code',
            field=models.CharField(default=b'', max_length=8),
        ),
    ]
