# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-25 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_otp_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='person',
        ),
    ]
