# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-25 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_otp_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Registration'),
        ),
    ]
