# Generated by Django 3.1.2 on 2020-10-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_otp_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='shop_code',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_description',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
